import { ProjectType } from './types';
import { quix, talentum, DomusAI, Bildin, Salud360Logo } from './components/Icons';

export const PROJECTS: ProjectType[] = [
  {
    id: 1,
    name: 'Domus AI',
    category: 'PropTech / AI',
    description: 'Run buildings on autopilot — Domus AI automates billing, maintenance, and resident support for property managers via WhatsApp.',
    longDescription: 'Domus AI automates billing, maintenance, and resident support for property managers via AI agents on WhatsApp and phone. Our platform helps teams reduce workload, improve cash flow, and deliver instant service — without adding staff or training.',
    features: [
      "9 active clients and $2.5K in (MRR) across Peru, Paraguay, and Mexico.",
      "AI agents handle collections, incident reports, visitor access, and resident inquiries",
      "Integrated with leading SaaS tools — no downloads, no learning curve",
      "Backed by UTEC Ventures, Snitch Ventures, and angel investors",
      "Founders: ex-Zoho COO and $1.4M ARR spin-off CEO; serial entrepreneurs with SaaS and AI experience"
    ],
    extraParagraph: 'Our vision: to become the AI-powered operating system for buildings — enabling fully automated, scalable property management for a vertical future.',
    logoIncludesName: true,
    logo: DomusAI, 
    calendlyLink: 'https://calendly.com/utec-ventures/domus-ai-intro',
    teamSize: 2,
    founders: [
      { name: 'Samuele Soto Cannatà', title: 'CEO & Founder', imageUrl: 'https://media.licdn.com/dms/image/v2/D4E03AQErR1xGAZWBBQ/profile-displayphoto-crop_800_800/B4EZf.w4O8H4AI-/0/1752325918783?e=1757548800&v=beta&t=3jLGqlruKARrnv5wCQ0rXWZzrx48Hw1_O7FliUrEFcw', linkedinUrl: 'https://www.linkedin.com/in/samuelescb/', description: 'Delivering AI agents to automate every building in the world.' },
      { name: 'Piero Luis Arévalo', title: 'COO & Co-founder', imageUrl: 'https://media.licdn.com/dms/image/v2/D4E03AQHdDeXlvxVdkA/profile-displayphoto-shrink_800_800/B4EZWz5pVAGgBs-/0/1742479988385?e=1757548800&v=beta&t=JrgsJVWe1i_2A5NsUON6qyZPV_si98pjc_WURRQFRzA', linkedinUrl: 'https://www.linkedin.com/in/piero-luis-ar%C3%A9valo-355ab5143?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3B2evM2dTwR6CXE37tI3Nrsg%3D%3D', description: 'With over 10 years of experience in senior management roles, Scrum Master, and Product Owner, I have led digitization and digital transformation projects, with a special focus on optimizing processes in marketing, sales, and operations departments at companies of various sizes. My experience in agile project management is complemented by a strong specialization in CRM and CX implementation strategies. I currently serve as partner and COO at Grupo M4G, a Zoho Corporation Premium Partner in Peru, and as COO at Domus AI, where I lead the operation and creation of innovative technologies in building management.' },
    ],
    imageUrl: '/src/assets/visual/visual_domus.png',
    pdfUrl: '/src/assets/pdfs/domus.pdf',
  },
  {
    id: 2,
    name: 'Bildin',
    category: 'ConstructionTech / SaaS',
    description: 'Plataforma SaaS que optimiza la gestión en construcción con seguimiento en tiempo real de productividad y rendimiento para mejorar la eficiencia.',
    longDescription: 'Bildin es un software basado en la nube para la gestión de recursos en la construcción. Nuestra plataforma permite a los gerentes de proyecto monitorear el progreso, administrar equipos y optimizar la asignación de recursos en tiempo real, lo que lleva a una mayor eficiencia y a la finalización de proyectos a tiempo y dentro del presupuesto.',
    features: [
      "Seguimiento de productividad en tiempo real.",
      "Gestión de equipos y asignación de tareas.",
      "Control de inventario de materiales.",
      "Reportes de rendimiento detallados."
    ],
    extraParagraph: '',
    logoIncludesName: true,
    logo: Bildin,
    calendlyLink: 'https://calendly.com/utec-ventures/bildin-intro',
    teamSize: 2,
    founders: [
      { name: 'Matías Calmet Arana Cisneros', title: 'CEO & Co-founder', imageUrl: 'https://media.licdn.com/dms/image/v2/D4E03AQENSbTTnyi_mQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1728092120239?e=1757548800&v=beta&t=aoldIGKKonk7_I_2o1UT-vF_Enp96Ti4kqPvNj1tQ9U', linkedinUrl: 'https://www.linkedin.com/in/mat%C3%ADas-calmet-arana-cisneros-a1107b177/', description: 'Civil engineer co-founder of Bildin, software as a service that integrates and optimizes planning , cost and quality processes for building projects in the construction phase.' },
      { name: 'Ana Paula Gamarra Casalino', title: 'Co-founder', imageUrl: 'https://media.licdn.com/dms/image/v2/C4E03AQEXHeEG5DU77g/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1642873282331?e=1757548800&v=beta&t=u3MG5wYLRTYacUAyrWtKieUzg0jnRP85qQSbng3ePIo', linkedinUrl: 'https://www.linkedin.com/in/anagamarra/', description: '' },
      { name: 'Alejandro Goicochea', title: 'CTO', imageUrl: 'https://media.licdn.com/dms/image/v2/D4E03AQFJGmKfjdC4rQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1721696619751?e=1757548800&v=beta&t=SFZ1QbSXiN7aQyPVqZy_d2_jOwgevoBrbi2ozzD90oI', linkedinUrl: 'https://www.linkedin.com/in/alejandrogh97/', description: "I am a software developer with over 3 years of experience and outstanding skills in critical thinking and problem-solving. Additionally, I hold a Bachelor's degree in Computer Science and possess an advanced level of English. My interest lies in participating in software development projects where I can be involved in the entire product creation process and deliver value to customers." },
    ],
    imageUrl: '/src/assets/visual/visual_bildin.png',
    pdfUrl: '',
  },
  {
    id: 3,
    name: 'Talentum',
    category: 'HR Tech / AI',
    description: 'Creamos a Sara, una reclutadora con IA que encuentra, evalúa y contacta a miles de candidatos en segundos, ahorrando tiempo y costos.',
    longDescription: 'Talentum presenta a Sara, una reclutadora impulsada por IA diseñada para transformar el proceso de adquisición de talento. Sara automatiza la búsqueda, el filtrado y la comunicación inicial con los candidatos, permitiendo a los equipos de RRHH centrarse en los aspirantes más cualificados y reducir drásticamente el tiempo de contratación.',
    features: [
      "Reclutamiento masivo automatizado.",
      "Evaluación inteligente de perfiles.",
      "Interacción inicial vía chatbots.",
      "Ahorro significativo en costos de contratación."
    ],
    extraParagraph: '',
    logoIncludesName: true,
    logo: talentum,
    calendlyLink: 'https://calendly.com/utec-ventures/talentum-intro',
    teamSize: 3,
    founders: [
      { name: 'Joaquin Titievsky', title: 'CEO & Co-founder', imageUrl: 'https://media.licdn.com/dms/image/v2/D4D03AQHWglsLqM_Qaw/profile-displayphoto-shrink_800_800/B4DZV3yf62G8Ac-/0/1741471481910?e=1757548800&v=beta&t=Wjfd7SgPxY-zLgJC4ZZwR6ZpmnaYYBZPtBpc30uaQc8', linkedinUrl: 'https://www.linkedin.com/in/joaquin-titievsky/', description: '' },
      { name: 'Ionatan Engelsberg', title: 'CTO & Co-Founder', imageUrl: 'https://media.licdn.com/dms/image/v2/D4D03AQHvQl2mjnlSEw/profile-displayphoto-shrink_800_800/B4DZV3ziXWHAAg-/0/1741471754231?e=1757548800&v=beta&t=fw-e8aPFmRpOgL2R5TXd_Ls2tEuGNCuy4HGvheef_cI', linkedinUrl: 'https://www.linkedin.com/in/ionatan-engelsberg/', description: 'With a strong background in software engineering and hands-on experience in machine learning, I am passionate about bridging the gap between data engineering and AI to deliver data-driven real value. My journey has equipped me with expertise in API development, database design and management, and developing cutting-edge computer vision deep learning models, RAG chatbots, and end-to-end data pipelines.' },
      { name: 'Martin Lipovetzky', title: 'Co-Founder', imageUrl: 'https://media.licdn.com/dms/image/v2/D4D03AQEoaRaMvFHGNA/profile-displayphoto-shrink_800_800/B4DZWBgQUIHkAc-/0/1741634471636?e=1757548800&v=beta&t=kOWhh8Qq_Y-sjOL2sUOZ4mqTb52vGUBWlzqa-MFBzLw', linkedinUrl: 'https://www.linkedin.com/in/martin-lipovetzky-b23b5823b/', description: '' },
    ],
    imageUrl: '/src/assets/visual/visual_talentum.png',
    pdfUrl: '',
  },
  {
    id: 4,
    name: 'Quix',
    category: 'EdTech / AI',
    description: 'Educación corporativa a medida a través de WhatsApp. Creamos cursos en horas con videos generados por IA para capacitar equipos de forma ágil.',
    longDescription: 'Quix reinventa la capacitación corporativa utilizando la IA para crear y distribuir micro-cursos a través de WhatsApp. Nuestra plataforma permite a las empresas desarrollar contenido de formación personalizado en cuestión de horas, facilitando un aprendizaje ágil y accesible directamente en los dispositivos móviles de los empleados.',
    features: [
      "Creación de cursos en horas, no semanas.",
      "Distribución de contenido vía WhatsApp.",
      "Videos y materiales generados por IA.",
      "Micro-learning para mayor retención."
    ],
    extraParagraph: '',
    logoIncludesName: true,
    logo: quix,
    calendlyLink: 'https://calendly.com/utec-ventures/quix-intro',
    teamSize: 4,
    founders: [
      { name: 'Ignacio Barrea', title: 'CEO & Co-founder', imageUrl: 'https://media.licdn.com/dms/image/v2/D4D03AQEj2HCQiN_nJg/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1718273951825?e=1757548800&v=beta&t=tce9LxjxwgMZDm7c2wNoH6MEoKeOA1NzJ4iAAAGF_1s', linkedinUrl: 'https://www.linkedin.com/in/ignaciobarrea/', description: "At Quix, we're pioneering AI-enhanced educational solutions that transform how individuals and organizations learn and grow. My expertise in product development and strategic planning, honed over a decade in tech startups, is central to our mission of advancing learning technologies. Our approach is rooted in agile methodologies and data-driven decision-making, ensuring that our offerings are both innovative and effective." },
      { name: 'Carlos Alarcón', title: 'CTO & Co-founder', imageUrl: 'https://media.licdn.com/dms/image/v2/D4E03AQE_SuNj6_BDGQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1705954672368?e=1757548800&v=beta&t=p-55WIUA-qa6DW96Cm2-kQozlDnjTRNvvdYZtlqUt9k', linkedinUrl: 'https://www.linkedin.com/in/alarcon7a/', description: '' },
      { name: 'Julia Insua', title: 'CFO & Co-founder', imageUrl: 'https://media.licdn.com/dms/image/v2/D4D03AQGLnqK7xbznuA/profile-displayphoto-crop_800_800/B4DZf8f5qPH8AI-/0/1752287911462?e=1757548800&v=beta&t=hVkdEydiBPbYBTXOrHEkfRQMoqhEYjyAOBd4SNMT9ME', linkedinUrl: 'https://www.linkedin.com/in/julia-insua/', description: 'I believe in the power of startups to transform industries, and my mission is to give them the financial structure they need to scale successfully. As Co-Founder and CFO of Quix, I know the secret lies in combining data, strategy, and vision. With over eight years of experience working with globally expanding startups, I have built robust financial models, efficient tax structures, and optimized due diligence processes from the ground up, enabling agile and sustainable growth. My focus on process optimization ensures accurate and timely financial information, which is key to decision-making in dynamic environments.' },
      { name: 'Santiago Gómez Osorio', title: 'CRO & Co-Founder', imageUrl: 'https://media.licdn.com/dms/image/v2/C4D03AQFw7l1P3d9G2w/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1604692538151?e=1757548800&v=beta&t=AnGQB41hZS_HDBC5jZLPOygpY2RDGzMxIUSeQRjHMk0', linkedinUrl: 'https://www.linkedin.com/in/santiagogomezosorio/', description: '' },
    ],
    imageUrl: '/src/assets/visual/visual_quix.png',
    pdfUrl: '',
  },
  {
    id: 5,
    name: 'Vera',
    category: 'HealthTech / SaaS',
    description: 'Vera automates financial risk assessments, helping banks make credit decisions 100x faster — from 60 days to just hours.',
    longDescription: 'Vera is the new highway for banks, lenders, and enterprises to turn data into fast, actionable credit decisions. Our AI-powered platform automates financial risk assessments, reducing underwriting time from 60 days to just a few hours — giving traditional institutions fintech-level speed and efficiency.',
    features: [
      "100x faster credit decisions — from weeks to hours",
      "Live beta with pilot banks in progress",
      "Herramientas de seguimiento de progreso emocional.",
      "Acceso a recursos y materiales de autoayuda."
    ],
    extraParagraph: '',
    logoIncludesName: true,
    logo: Salud360Logo,
    calendlyLink: 'https://calendly.com/utec-ventures/vera-intro',
    teamSize: 2,
    founders: [
      { name: 'Founder Ocho', title: 'CEO & Co-founder', imageUrl: 'https://i.pravatar.cc/150?u=vera1', linkedinUrl: '#', description: 'Impulsa la misión de Vera de hacer accesible la salud mental de calidad, combinando experiencia en el sector salud y gestión empresarial.' },
      { name: 'Founder Nueve', title: 'CPO & Co-founder', imageUrl: 'https://i.pravatar.cc/150?u=vera2', linkedinUrl: '#', description: 'Responsable del producto y la tecnología, enfocado en desarrollar el algoritmo de matching y una plataforma segura y fácil de usar para pacientes y terapeutas.' },
    ],
    imageUrl: '/src/assets/visual/visual_vera.png',
    pdfUrl: '',
  },
  {
    id: 5,
    name: 'NOS',
    category: 'HealthTech / SaaS',
    description: 'Plataforma SaaS que conecta pacientes con especialistas de la salud mental a través de un matching con IA para terapias más efectivas.',
    longDescription: 'Vera es una plataforma de bienestar emocional que utiliza inteligencia artificial para conectar a las personas con el psicólogo o terapeuta ideal para sus necesidades. A través de un cuestionario detallado y algoritmos de matching, aseguramos una alta compatibilidad, mejorando la adherencia y los resultados de la terapia. Ofrecemos sesiones online seguras y un seguimiento continuo del progreso.',
    features: [
      "Matching inteligente entre pacientes y terapeutas.",
      "Sesiones de terapia online 100% seguras y confidenciales.",
      "Herramientas de seguimiento de progreso emocional.",
      "Acceso a recursos y materiales de autoayuda."
    ],
    extraParagraph: '',
    logoIncludesName: true,
    logo: Salud360Logo,
    calendlyLink: 'https://calendly.com/utec-ventures/vera-intro',
    teamSize: 2,
    founders: [
      { name: 'Founder Ocho', title: 'CEO & Co-founder', imageUrl: 'https://i.pravatar.cc/150?u=vera1', linkedinUrl: '#', description: 'Impulsa la misión de Vera de hacer accesible la salud mental de calidad, combinando experiencia en el sector salud y gestión empresarial.' },
      { name: 'Founder Nueve', title: 'CPO & Co-founder', imageUrl: 'https://i.pravatar.cc/150?u=vera2', linkedinUrl: '#', description: 'Responsable del producto y la tecnología, enfocado en desarrollar el algoritmo de matching y una plataforma segura y fácil de usar para pacientes y terapeutas.' },
    ],
    imageUrl: '/src/assets/visual/visual_nos.png',
    pdfUrl: '',
  },
];